### ISSUE TITLE
'npm install' just makes errors.

### ISSUE THREAD

**Issue by magic-thomas** [videojs/videojs-contrib-ads#540]
### Description

npm install goes error.

### Steps to Reproduce
```sh 
git clone https://github.com/videojs/videojs-contrib-ads.git 
cd videojs-contrib-ads
 ( rm package-lock.json ) 
npm install

```
#### Expected Results

success to install packages.

#### Actual Results

it shows errors.

```sh
npm WARN deprecated rollup-plugin-multi-entry@2.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-multi-entry.
npm WARN deprecated rollup-plugin-json@3.1.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
npm WARN deprecated rollup-plugin-node-resolve@4.2.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated date-format@2.1.0: 2.x is no longer supported. Please upgrade to 4.x or higher.
npm WARN deprecated rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated streamroller@1.0.6: 1.x is no longer supported. Please upgrade to 3.x or higher.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated log4js@4.5.1: 4.x is no longer supported. Please upgrade to 6.x or higher.
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /video-ad/videojs-contrib-ads/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c -- node scripts/build.js
npm ERR! Building: /usr/bin/node /video-ad/videojs-contrib-ads/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/video-ad/videojs-contrib-ads/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.18.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/video-ad/videojs-contrib-ads/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/video-ad/videojs-contrib-ads/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/video-ad/videojs-contrib-ads/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/video-ad/videojs-contrib-ads/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/video-ad/videojs-contrib-ads/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/video-ad/videojs-contrib-ads/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/video-ad/videojs-contrib-ads/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/video-ad/videojs-contrib-ads/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/video-ad/videojs-contrib-ads/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/video-ad/videojs-contrib-ads/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/video-ad/videojs-contrib-ads/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/video-ad/videojs-contrib-ads/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /video-ad/videojs-contrib-ads/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/video-ad/videojs-contrib-ads/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/video-ad/videojs-contrib-ads/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/video-ad/videojs-contrib-ads/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/video-ad/videojs-contrib-ads/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /video-ad/videojs-contrib-ads/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /video-ad/videojs-contrib-ads/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /video-ad/videojs-contrib-ads/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp ERR! System Linux 5.4.0-131-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/video-ad/videojs-contrib-ads/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /video-ad/videojs-contrib-ads/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.18.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /video-ad/.npm/_logs/2022-10-27T15_51_16_203Z-debug-0.log

```

### Versions

npm : 8.19.2
node : v16.18.0
videojs-contrib-ads : t6.9.0.

### Platforms

Mac M1 / Ubuntu 20.04 LTS

Which version of npm should used for 'install' and 'build' ?

**Comment by magic-thomas** [comment]
Solved. 

node 14 is ok. 

sorry for wasting your time.
